language: csharp
dotnet: 3.1.402
solution: MimeKit.sln
install:
  - dotnet restore MimeKit.sln
script:
  - msbuild /p:Configuration=Debug /p:MonoRuntime=true MimeKit.sln
  - mono ~/.nuget/packages/nunit.consolerunner/3.11.1/tools/nunit3-console.exe UnitTests/bin/Debug/net48/UnitTests.dll
